In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
df=pd.read_csv('heart_disease.csv')

In [37]:
df.sample(10)

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
234,235,54,Female,Cleveland,non-anginal,160.0,201.0,False,normal,163.0,False,0.0,upsloping,1.0,normal,0
887,888,69,Male,VA Long Beach,non-anginal,NaN,271.0,False,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
157,158,58,Male,Cleveland,asymptomatic,125.0,300.0,False,lv hypertrophy,171.0,False,0.0,upsloping,2.0,reversable defect,1
305,306,29,Male,Hungary,atypical angina,140.0,NaN,False,normal,170.0,False,0.0,NaN,NaN,NaN,0
723,724,55,Male,VA Long Beach,asymptomatic,142.0,228.0,False,st-t abnormality,149.0,True,2.5,upsloping,NaN,NaN,1
401,402,48,Male,Hungary,atypical angina,130.0,245.0,False,normal,160.0,False,0.0,NaN,NaN,NaN,0
877,878,72,Male,VA Long Beach,asymptomatic,160.0,NaN,True,lv hypertrophy,130.0,False,1.5,NaN,NaN,NaN,2
793,794,54,Male,VA Long Beach,asymptomatic,136.0,220.0,False,normal,140.0,True,3.0,flat,NaN,NaN,3
519,520,54,Male,Hungary,asymptomatic,125.0,216.0,False,normal,140.0,False,0.0,NaN,NaN,NaN,1
83,84,68,Male,Cleveland,non-anginal,180.0,274.0,True,lv hypertrophy,150.0,True,1.6,flat,0.0,reversable defect,3

In [38]:
df.shape

(920, 16)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [40]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [41]:
df.columns

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [50]:
df.isna().sum()[df.isna().sum()>0].sort_values(ascending=False)

ca          611
thal        486
slope       309
fbs          90
oldpeak      62
trestbps     59
exang        55
thalch       55
chol         30
restecg       2
dtype: int64

In [101]:
print(df.duplicated().sum())

0

In [57]:
print('Max Age = ',df['age'].max())
print('Min Age = ',df['age'].min())
print('Avg Age = ',df['age'].mean().round(2))

Max Age =  77
Min Age =  28
Avg Age =  53.51

In [58]:
df['sex'].value_counts()

sex
Male      726
Female    194
Name: count, dtype: int64

In [69]:
print("Male percentage = ",((df['sex']=='Male').sum()/920*100).round(2),"%")
print('Female percentage = ',((df['sex']=='Female').sum()/920*100).round(2),"%")

Male percentage =  78.91 %
Female percentage =  21.09 %

In [70]:
df['dataset'].unique()

array(['Cleveland', 'Hungary', 'Switzerland', 'VA Long Beach'],
      dtype=object)

In [71]:
df['dataset'].value_counts()

dataset
Cleveland        304
Hungary          293
VA Long Beach    200
Switzerland      123
Name: count, dtype: int64

In [79]:
print("Most data has been collected from =",df['dataset'].value_counts().idxmax())

Most data has been collected from = Cleveland

In [82]:
df['cp'].unique()

array(['typical angina', 'asymptomatic', 'non-anginal', 'atypical angina'],
      dtype=object)

In [83]:
df['cp'].value_counts()

cp
asymptomatic       496
non-anginal        204
atypical angina    174
typical angina      46
Name: count, dtype: int64

In [97]:
print(f'Typical angina patient = {(df['cp']=='typical angina').sum()/920*100:.2f}%')
print(f'Atypical angina patient = {(df['cp']=='atypical angina').sum()/920*100:.2f}%')
print(f'Non-Anginal patient = {(df['cp']=='non-anginal').sum()/920*100:.2f}%')
print(f'Asymptomatic patient = {(df['cp']=='asymptomatic').sum()/920*100:.2f}%\n')
print("'Most Patient has No Chest Pain'")

Typical angina patient = 5.00%
Atypical angina patient = 18.91%
Non-Anginal patient = 22.17%
Asymptomatic patient = 53.91%

'Most Patient has No Chest Pain'

In [ ]:
sns